### ISSUE TITLE
Error with frequency spec in data handler

### ISSUE THREAD

**Issue by toddkarin** [slacgismo/solar-data-tools#14]
I got an error in line 281 in data_handler.py
```
            new_index = pd.date_range(start=self.day_index[0].date(),
                                      end=self.day_index[-1].date() + timedelta(
                                          days=1),
                                      freq='{}s'.format(freq))[:-1]
```
The error is:
```
Traceback (most recent call last):
  File "/Users/toddkarin/anaconda3/envs/pvpro/lib/python3.8/site-packages/pandas/tseries/frequencies.py", line 169, in to_offset
    stride = int(stride)
ValueError: invalid literal for int() with base 10: '60.0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/toddkarin/Box/projects_Todd_Karin/pvpro/pvpro/main.py", line 1363, in run_preprocess
    self.dh.run_pipeline(power_col='power_dc',
  File "/Users/toddkarin/Box/projects_Todd_Karin/solar-data-tools/solardatatools/data_handler.py", line 281, in run_pipeline
    new_index = pd.date_range(start=self.day_index[0].date(),
  File "/Users/toddkarin/anaconda3/envs/pvpro/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 1172, in date_range
    dtarr = DatetimeArray._generate_range(
  File "/Users/toddkarin/anaconda3/envs/pvpro/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 362, in _generate_range
    freq = to_offset(freq)
  File "/Users/toddkarin/anaconda3/envs/pvpro/lib/python3.8/site-packages/pandas/tseries/frequencies.py", line 177, in to_offset
    raise ValueError(libfreqs.INVALID_FREQ_ERR_MSG.format(freq))
ValueError: Invalid frequency: 60.0s
```

The problem is that the frequency spec is '60.0s' when it should really be '60s'.

I fixed this by adding int() around freq, but not sure if there's a better way.

**Comment by bmeyers** [comment]
Fixed in current version
